platform :ios, '9.3'
target 'adessoIndoorNavigator' do
  use_frameworks!
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

end
